name: Update Progress

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  push:
    paths:
      - 'questions/**'

jobs:
  update-heatmap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create graph
        run: python3 update_status.py


